# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Cheng\Google Drive\GitHub\CryoPy\Equipment\DualGateSweep.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 763)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mapView = QtWidgets.QGraphicsView(self.centralwidget)
        self.mapView.setGeometry(QtCore.QRect(35, 15, 500, 500))
        self.mapView.setObjectName("mapView")
        self.lineView = QtWidgets.QGraphicsView(self.centralwidget)
        self.lineView.setGeometry(QtCore.QRect(35, 520, 500, 200))
        self.lineView.setObjectName("lineView")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(550, 690, 291, 21))
        self.filename.setObjectName("filename")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(560, 20, 276, 651))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.initialize = QtWidgets.QPushButton(self.widget)
        self.initialize.setObjectName("initialize")
        self.verticalLayout_3.addWidget(self.initialize)
        self.start = QtWidgets.QPushButton(self.widget)
        self.start.setObjectName("start")
        self.verticalLayout_3.addWidget(self.start)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelG1 = QtWidgets.QLabel(self.widget)
        self.labelG1.setObjectName("labelG1")
        self.horizontalLayout_10.addWidget(self.labelG1)
        self.labelG2 = QtWidgets.QLabel(self.widget)
        self.labelG2.setObjectName("labelG2")
        self.horizontalLayout_10.addWidget(self.labelG2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gate1 = QtWidgets.QComboBox(self.widget)
        self.gate1.setObjectName("gate1")
        self.gate1.addItem("")
        self.horizontalLayout_3.addWidget(self.gate1)
        self.gate2 = QtWidgets.QComboBox(self.widget)
        self.gate2.setObjectName("gate2")
        self.gate2.addItem("")
        self.horizontalLayout_3.addWidget(self.gate2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelMinV2 = QtWidgets.QLabel(self.widget)
        self.labelMinV2.setObjectName("labelMinV2")
        self.gridLayout.addWidget(self.labelMinV2, 0, 1, 1, 1)
        self.labelMaxV1 = QtWidgets.QLabel(self.widget)
        self.labelMaxV1.setObjectName("labelMaxV1")
        self.gridLayout.addWidget(self.labelMaxV1, 2, 0, 1, 1)
        self.labelMaxV2 = QtWidgets.QLabel(self.widget)
        self.labelMaxV2.setObjectName("labelMaxV2")
        self.gridLayout.addWidget(self.labelMaxV2, 2, 1, 1, 1)
        self.labelIncrementV1 = QtWidgets.QLabel(self.widget)
        self.labelIncrementV1.setObjectName("labelIncrementV1")
        self.gridLayout.addWidget(self.labelIncrementV1, 4, 0, 1, 1)
        self.labelIncrementV2 = QtWidgets.QLabel(self.widget)
        self.labelIncrementV2.setObjectName("labelIncrementV2")
        self.gridLayout.addWidget(self.labelIncrementV2, 4, 1, 1, 1)
        self.increment1 = QtWidgets.QLineEdit(self.widget)
        self.increment1.setObjectName("increment1")
        self.gridLayout.addWidget(self.increment1, 5, 0, 1, 1)
        self.delay2 = QtWidgets.QLineEdit(self.widget)
        self.delay2.setObjectName("delay2")
        self.gridLayout.addWidget(self.delay2, 7, 1, 1, 1)
        self.labelMinV1 = QtWidgets.QLabel(self.widget)
        self.labelMinV1.setObjectName("labelMinV1")
        self.gridLayout.addWidget(self.labelMinV1, 0, 0, 1, 1)
        self.increment2 = QtWidgets.QLineEdit(self.widget)
        self.increment2.setObjectName("increment2")
        self.gridLayout.addWidget(self.increment2, 5, 1, 1, 1)
        self.delay1 = QtWidgets.QLineEdit(self.widget)
        self.delay1.setObjectName("delay1")
        self.gridLayout.addWidget(self.delay1, 7, 0, 1, 1)
        self.minV1 = QtWidgets.QLineEdit(self.widget)
        self.minV1.setObjectName("minV1")
        self.gridLayout.addWidget(self.minV1, 1, 0, 1, 1)
        self.minV2 = QtWidgets.QLineEdit(self.widget)
        self.minV2.setObjectName("minV2")
        self.gridLayout.addWidget(self.minV2, 1, 1, 1, 1)
        self.maxV2 = QtWidgets.QLineEdit(self.widget)
        self.maxV2.setObjectName("maxV2")
        self.gridLayout.addWidget(self.maxV2, 3, 1, 1, 1)
        self.maxV1 = QtWidgets.QLineEdit(self.widget)
        self.maxV1.setObjectName("maxV1")
        self.gridLayout.addWidget(self.maxV1, 3, 0, 1, 1)
        self.labelDelay1 = QtWidgets.QLabel(self.widget)
        self.labelDelay1.setObjectName("labelDelay1")
        self.gridLayout.addWidget(self.labelDelay1, 6, 0, 1, 1)
        self.labelDelay2 = QtWidgets.QLabel(self.widget)
        self.labelDelay2.setObjectName("labelDelay2")
        self.gridLayout.addWidget(self.labelDelay2, 6, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labell1 = QtWidgets.QLabel(self.widget1)
        self.labell1.setObjectName("labell1")
        self.horizontalLayout_13.addWidget(self.labell1)
        self.label1ChA = QtWidgets.QLabel(self.widget1)
        self.label1ChA.setObjectName("label1ChA")
        self.horizontalLayout_13.addWidget(self.label1ChA)
        self.label1ChB = QtWidgets.QLabel(self.widget1)
        self.label1ChB.setObjectName("label1ChB")
        self.horizontalLayout_13.addWidget(self.label1ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lockin1 = QtWidgets.QComboBox(self.widget1)
        self.lockin1.setObjectName("lockin1")
        self.horizontalLayout_2.addWidget(self.lockin1)
        self.lockin1ChA = QtWidgets.QComboBox(self.widget1)
        self.lockin1ChA.setObjectName("lockin1ChA")
        self.horizontalLayout_2.addWidget(self.lockin1ChA)
        self.lockin1ChB = QtWidgets.QComboBox(self.widget1)
        self.lockin1ChB.setObjectName("lockin1ChB")
        self.horizontalLayout_2.addWidget(self.lockin1ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label2 = QtWidgets.QLabel(self.widget1)
        self.label2.setObjectName("label2")
        self.horizontalLayout_12.addWidget(self.label2)
        self.label2ChA = QtWidgets.QLabel(self.widget1)
        self.label2ChA.setObjectName("label2ChA")
        self.horizontalLayout_12.addWidget(self.label2ChA)
        self.label2ChB = QtWidgets.QLabel(self.widget1)
        self.label2ChB.setObjectName("label2ChB")
        self.horizontalLayout_12.addWidget(self.label2ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lockin2 = QtWidgets.QComboBox(self.widget1)
        self.lockin2.setObjectName("lockin2")
        self.horizontalLayout_4.addWidget(self.lockin2)
        self.lockin2ChA = QtWidgets.QComboBox(self.widget1)
        self.lockin2ChA.setObjectName("lockin2ChA")
        self.horizontalLayout_4.addWidget(self.lockin2ChA)
        self.lockin2ChB = QtWidgets.QComboBox(self.widget1)
        self.lockin2ChB.setObjectName("lockin2ChB")
        self.horizontalLayout_4.addWidget(self.lockin2ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label3 = QtWidgets.QLabel(self.widget1)
        self.label3.setObjectName("label3")
        self.horizontalLayout_14.addWidget(self.label3)
        self.label3ChA = QtWidgets.QLabel(self.widget1)
        self.label3ChA.setObjectName("label3ChA")
        self.horizontalLayout_14.addWidget(self.label3ChA)
        self.label3ChB = QtWidgets.QLabel(self.widget1)
        self.label3ChB.setObjectName("label3ChB")
        self.horizontalLayout_14.addWidget(self.label3ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lockin3 = QtWidgets.QComboBox(self.widget1)
        self.lockin3.setObjectName("lockin3")
        self.horizontalLayout_5.addWidget(self.lockin3)
        self.lockin3ChA = QtWidgets.QComboBox(self.widget1)
        self.lockin3ChA.setObjectName("lockin3ChA")
        self.horizontalLayout_5.addWidget(self.lockin3ChA)
        self.lockin3ChB = QtWidgets.QComboBox(self.widget1)
        self.lockin3ChB.setObjectName("lockin3ChB")
        self.horizontalLayout_5.addWidget(self.lockin3ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label4 = QtWidgets.QLabel(self.widget1)
        self.label4.setObjectName("label4")
        self.horizontalLayout_15.addWidget(self.label4)
        self.label4ChA = QtWidgets.QLabel(self.widget1)
        self.label4ChA.setObjectName("label4ChA")
        self.horizontalLayout_15.addWidget(self.label4ChA)
        self.label4ChB = QtWidgets.QLabel(self.widget1)
        self.label4ChB.setObjectName("label4ChB")
        self.horizontalLayout_15.addWidget(self.label4ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lockin4 = QtWidgets.QComboBox(self.widget1)
        self.lockin4.setObjectName("lockin4")
        self.horizontalLayout_6.addWidget(self.lockin4)
        self.lockin4ChA = QtWidgets.QComboBox(self.widget1)
        self.lockin4ChA.setObjectName("lockin4ChA")
        self.horizontalLayout_6.addWidget(self.lockin4ChA)
        self.lockin4ChB = QtWidgets.QComboBox(self.widget1)
        self.lockin4ChB.setObjectName("lockin4ChB")
        self.horizontalLayout_6.addWidget(self.lockin4ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label5 = QtWidgets.QLabel(self.widget1)
        self.label5.setObjectName("label5")
        self.horizontalLayout_16.addWidget(self.label5)
        self.label5ChA = QtWidgets.QLabel(self.widget1)
        self.label5ChA.setObjectName("label5ChA")
        self.horizontalLayout_16.addWidget(self.label5ChA)
        self.label5ChB = QtWidgets.QLabel(self.widget1)
        self.label5ChB.setObjectName("label5ChB")
        self.horizontalLayout_16.addWidget(self.label5ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lockin5 = QtWidgets.QComboBox(self.widget1)
        self.lockin5.setObjectName("lockin5")
        self.horizontalLayout_7.addWidget(self.lockin5)
        self.lockin5ChA = QtWidgets.QComboBox(self.widget1)
        self.lockin5ChA.setObjectName("lockin5ChA")
        self.horizontalLayout_7.addWidget(self.lockin5ChA)
        self.lockin5ChB = QtWidgets.QComboBox(self.widget1)
        self.lockin5ChB.setObjectName("lockin5ChB")
        self.horizontalLayout_7.addWidget(self.lockin5ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label6 = QtWidgets.QLabel(self.widget1)
        self.label6.setObjectName("label6")
        self.horizontalLayout_17.addWidget(self.label6)
        self.label6ChA = QtWidgets.QLabel(self.widget1)
        self.label6ChA.setObjectName("label6ChA")
        self.horizontalLayout_17.addWidget(self.label6ChA)
        self.label6ChB = QtWidgets.QLabel(self.widget1)
        self.label6ChB.setObjectName("label6ChB")
        self.horizontalLayout_17.addWidget(self.label6ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lockin6 = QtWidgets.QComboBox(self.widget1)
        self.lockin6.setObjectName("lockin6")
        self.horizontalLayout_8.addWidget(self.lockin6)
        self.lockin6ChA = QtWidgets.QComboBox(self.widget1)
        self.lockin6ChA.setObjectName("lockin6ChA")
        self.horizontalLayout_8.addWidget(self.lockin6ChA)
        self.lockin6ChB = QtWidgets.QComboBox(self.widget1)
        self.lockin6ChB.setObjectName("lockin6ChB")
        self.horizontalLayout_8.addWidget(self.lockin6ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label7 = QtWidgets.QLabel(self.widget1)
        self.label7.setObjectName("label7")
        self.horizontalLayout_18.addWidget(self.label7)
        self.label7ChA = QtWidgets.QLabel(self.widget1)
        self.label7ChA.setObjectName("label7ChA")
        self.horizontalLayout_18.addWidget(self.label7ChA)
        self.label7ChB = QtWidgets.QLabel(self.widget1)
        self.label7ChB.setObjectName("label7ChB")
        self.horizontalLayout_18.addWidget(self.label7ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lockin7 = QtWidgets.QComboBox(self.widget1)
        self.lockin7.setObjectName("lockin7")
        self.horizontalLayout_9.addWidget(self.lockin7)
        self.lockin7ChA = QtWidgets.QComboBox(self.widget1)
        self.lockin7ChA.setObjectName("lockin7ChA")
        self.horizontalLayout_9.addWidget(self.lockin7ChA)
        self.lockin7ChB = QtWidgets.QComboBox(self.widget1)
        self.lockin7ChB.setObjectName("lockin7ChB")
        self.horizontalLayout_9.addWidget(self.lockin7ChB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 21))
        self.menubar.setObjectName("menubar")
        self.menuStart = QtWidgets.QMenu(self.menubar)
        self.menuStart.setObjectName("menuStart")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDirectory = QtWidgets.QAction(MainWindow)
        self.actionDirectory.setObjectName("actionDirectory")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuStart.addAction(self.actionDirectory)
        self.menuStart.addAction(self.actionQuit)
        self.menubar.addAction(self.menuStart.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filename.setText(_translate("MainWindow", "File Name"))
        self.initialize.setText(_translate("MainWindow", "Initialize"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.labelG1.setText(_translate("MainWindow", "Gate 1 GPIB"))
        self.labelG2.setText(_translate("MainWindow", "Gate 2 GPIB"))
        self.gate1.setItemText(0, _translate("MainWindow", "Gate1"))
        self.gate2.setItemText(0, _translate("MainWindow", "Gate2"))
        self.labelMinV2.setText(_translate("MainWindow", "MinV2 (V)"))
        self.labelMaxV1.setText(_translate("MainWindow", "MaxV1 (V)"))
        self.labelMaxV2.setText(_translate("MainWindow", "MaxV2 (V)"))
        self.labelIncrementV1.setText(_translate("MainWindow", "IncrementV1 (V)"))
        self.labelIncrementV2.setText(_translate("MainWindow", "IncrementV2 (V)"))
        self.increment1.setText(_translate("MainWindow", "Increment1"))
        self.delay2.setText(_translate("MainWindow", "Delay2"))
        self.labelMinV1.setText(_translate("MainWindow", "MinV1 (V)"))
        self.increment2.setText(_translate("MainWindow", "Increment2"))
        self.delay1.setText(_translate("MainWindow", "Delay1"))
        self.minV1.setText(_translate("MainWindow", "MinV1"))
        self.minV2.setText(_translate("MainWindow", "MinV2"))
        self.maxV2.setText(_translate("MainWindow", "MaxV2"))
        self.maxV1.setText(_translate("MainWindow", "MaxV1"))
        self.labelDelay1.setText(_translate("MainWindow", "Delay1 (s)"))
        self.labelDelay2.setText(_translate("MainWindow", "Delay2 (s)"))
        self.labell1.setText(_translate("MainWindow", "LockIn1"))
        self.label1ChA.setText(_translate("MainWindow", "ChA"))
        self.label1ChB.setText(_translate("MainWindow", "ChB"))
        self.label2.setText(_translate("MainWindow", "LockIn2"))
        self.label2ChA.setText(_translate("MainWindow", "ChA"))
        self.label2ChB.setText(_translate("MainWindow", "ChB"))
        self.label3.setText(_translate("MainWindow", "LockIn3"))
        self.label3ChA.setText(_translate("MainWindow", "ChA"))
        self.label3ChB.setText(_translate("MainWindow", "ChB"))
        self.label4.setText(_translate("MainWindow", "Lockin4"))
        self.label4ChA.setText(_translate("MainWindow", "ChA"))
        self.label4ChB.setText(_translate("MainWindow", "ChB"))
        self.label5.setText(_translate("MainWindow", "LockIn5"))
        self.label5ChA.setText(_translate("MainWindow", "ChA"))
        self.label5ChB.setText(_translate("MainWindow", "ChB"))
        self.label6.setText(_translate("MainWindow", "LockIn6"))
        self.label6ChA.setText(_translate("MainWindow", "ChA"))
        self.label6ChB.setText(_translate("MainWindow", "ChB"))
        self.label7.setText(_translate("MainWindow", "LockIn7"))
        self.label7ChA.setText(_translate("MainWindow", "ChA"))
        self.label7ChB.setText(_translate("MainWindow", "ChB"))
        self.menuStart.setTitle(_translate("MainWindow", "File"))
        self.actionDirectory.setText(_translate("MainWindow", "Directory"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

